# Generated by Django 4.0.3 on 2022-04-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0002_comment_contributor_issue_project_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('CO', 'contributor'), ('ST', 'staff member'), ('LE', 'project leader')], default='CO', max_length=4),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('FE', 'FRONT-END'), ('BE', 'BACK-END'), ('IO', 'IOS'), ('AN', 'ANDROID')], max_length=4),
        ),
    ]
