# Generated by Django 4.0.3 on 2022-04-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0003_alter_project_options_project_contributors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
