# Generated by Django 4.0.3 on 2022-04-08 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets_app', '0005_projects_alter_ticket_project_delete_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Issues',
        ),
    ]
